name: screen_brightness_platform_interface
description: A common platform interface for the screen_brightness plugin
version: 2.1.0
homepage: https://github.com/aaassseee/screen_brightness
repository: https://github.com/aaassseee/screen_brightness/tree/patch-1/screen_brightness_platform_interface
issue_tracker: https://github.com/aaassseee/screen_brightness/issues
publish_to: none

topics:
  - screen
  - monitor
  - brightness

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
